name: push to github
on:
  push:
    branches:
    - 'main'
jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@main

      - name: pwd
        run: pwd &&ls -l /home/runner/work/devops/devops && ls -l /home/runner/work/_actions 

      - name: Checkout https://github.com/vastxie/99AI.git
        uses: actions/checkout@v2
        with:
          path: 'vastxie'
          repository: 'vastxie/99AI' # 替换为目标仓库
          ref: 'main' # 替换为目标分支

      - name: test
        run: pwd && ls -l  

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "jsonhcstart"
          password: ${{ DOCKER_PASSWORD }}

      - name: build and push 
        run: |
          cd vastxie && docker build -t jsonhcstart/vastxie:${{ github.sha }} .
          docker push jsonhcstart/vastxie:${{ github.sha }}
