name: push to github
on:
  push:
    branches:
    - 'main'
jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout https://github.com/vastxie/99AI.git
        uses: vastxie/99AI@main  
        
      - name: Checkout Repository master branch
        uses: actions/checkout@main

      - name: pwd
        run: pwd && ls -l /home/runner/work

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "jsonhcstart"
          password: "HHq123456*"

      - name: Build and Push container images
        uses: docker/build-push-action@v4.0.0
        id: build-and-push
        with:
          push: true
          tags: jsonhcstart/topic:${{ github.sha }}
