name: push to github
on:
  workflow_dispatch:
  schedule:
    - cron: '30 16 * * *'

jobs:
  deploy:
    name: sync vastxie and build and push image
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@main

      - name: pwd
        run: pwd && ls -l  

      - name: Checkout https://github.com/vastxie/99AI.git
        uses: actions/checkout@v2
        with:
          path: 'vastxie'
          repository: 'vastxie/99AI' # 替换为目标仓库
          ref: 'main' # 替换为目标分支

      - name: replace picture
        run: |
          pwd && ls -l vastxie
          cp -a logo.png vastxie/public/logo.png 
          sed -i 's/AIWeb-Admin/lawweb-Admin/g' vastxie/public/admin/index.html
          grep "lawweb-Admin" vastxie/public/admin/index.html

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: download bucket from cos
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: download logo.png ./
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-shanghai

      - name: pwd
        run: pwd && ls -l

      - name: build and push 
        run: |
          cd vastxie && docker build -t registry.cn-hangzhou.aliyuncs.com/jsonhc/vastxie:latest .
          docker push registry.cn-hangzhou.aliyuncs.com/jsonhc/vastxie:latest
